<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Your own gallery!</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/header.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
  </head>
  <body>
    <div class="container-fluid mb-4">
      <header class="topbar">
        <div class="container">
          <div class="row">
            <!-- social icon-->
            <div class="col-sm-12">
              <ul class="social-network">
                <li><a class="waves-effect waves-dark" href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                <li><a class="waves-effect waves-dark" href="https://twitter.com/home?lang=en"><i class="fa fa-twitter"></i></a></li>
                <li><a class="waves-effect waves-dark" href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </header>
    <nav class="navbar navbar-expand-lg navbar-dark mx-background-top-linear">
      <div class="container">
        <a class="navbar-brand" href="#">Final Project IAW</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <?=$user?>
          </li>
          <li class="nav-item">
            <?=$log?>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/KrosanTenshi/">Contact us!</a>
          </li>
          <li class="nav-item">
            <?=$delete?>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-4">
  <div class="row">
    <?=$gallery?>
  </div>
  </div>
  <form action="upload" method="post" enctype="multipart/form-data">
      Select image to upload:
      <input type="file" name="fileToUpload" id="fileToUpload">
      <input type="submit" class="btn btn-success btn-lrg" value="Upload Image" name="submit">
  </form>
    <?=$res?>
</div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script src="bower_components/popper.js/dist/popper.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script>
    $(document).ready(function(){
      $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });

        $(".zoom").hover(function(){

    		$(this).addClass('transition');
    	}, function(){

    		$(this).removeClass('transition');
    	});
    });
    </script>
  </body>
</html>
