<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Your own gallery!</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/header.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
  </head>
  <body>
    <div class="container-fluid mb-4">
      <header class="topbar">
        <div class="container">
          <div class="row">
            <!-- social icon-->
            <div class="col-sm-12">
              <ul class="social-network">
                <li><a class="waves-effect waves-dark" href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                <li><a class="waves-effect waves-dark" href="https://twitter.com/home?lang=en"><i class="fa fa-twitter"></i></a></li>
                <li><a class="waves-effect waves-dark" href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </header>
    <nav class="navbar navbar-expand-lg navbar-dark mx-background-top-linear">
      <div class="container">
        <a class="navbar-brand" href="#">Final Project IAW</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="">**USERNAME**</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="login">**LOG**</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="register">**REGISTER**</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://blog.getbootstrap.com/">**RESERVED**</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-4">
  <div class="row">
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <a href="spy.php?link=<?=$link?>">
        <img  src="https://i.ytimg.com/vi/wCZ5TJCBWMg/maxresdefault.jpg" class="zoom img-fluid "  alt="">
      </a>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <a href="spy.php?link=<?=$link1?>">
        <img  src="https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2018/04/CGWd8yk-796x398.jpg" class="zoom img-fluid"  alt="">
      </a>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <a href="spy.php?link=<?=$link2?>">
        <img  src="https://hackernoon.com/drafts/q141s3xfs.png" class="zoom img-fluid " alt="">
      </a>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <a href="spy.php?link=<?=$link3?>">
        <img  src="https://cdn.freebiesupply.com/logos/thumbs/2x/java-logo.png" class="zoom img-fluid "  alt="">
      </a>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <a href="spy.php?link=<?=$link4?>">
        <img  src="https://engineering.fb.com/wp-content/uploads/2015/06/1522635669452_11.jpg" class="zoom img-fluid "  alt="">
      </a>
    </div>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <a href="spy.php?link=<?=$link5?>">
        <img  src="https://cdn.lynda.com/course/139988/139988-637021525148800194-16x9.jpg" class="zoom img-fluid "  alt="">
      </a>
    </div>
  </div>

  </div>
</div>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script src="bower_components/popper.js/dist/popper.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script>
    $(document).ready(function(){
      $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });

        $(".zoom").hover(function(){

    		$(this).addClass('transition');
    	}, function(){

    		$(this).removeClass('transition');
    	});
    });
    </script>
  </body>
</html>
