<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
  <title>New Pasword</title>
  <style>
  body {
    background-color: #000000;
    font-family:"Trebuchet MS", Helvetica, sans-serif'
  }
  </style>
</head>
<body>
  <div class="container" style="margin-top:1vh">
    <div class="jumbotron mt-4 bg-secondary text-white text-center">
      <h1 class="display-5 text-center font-weight-bold">Recover your lost password</h1>
    </div>
  </div>
  <div class="container">
    <div class="jumbotron mt-4 bg-secondary text-white text-center">
      <form action="recovery" method="POST" class="text-center">
        <p class="h3 mb-4">Insert the e-mail registered with us:</p>
        <p class="mb-4">We will send you a new confirmation mail</p>
        <label for="mail">Email:</label>
        <input type="text" id="mail" name="mail" required class="form-control mb-4 <?=$val_e?>" placeholder="example@somedomain.com">
        <p class="text-center text-dark font-weight-bold mt-2"><?=$w_mail?></p>
        <button class="btn btn-success btn-lrg" type="submit">Resend!</button>
      </form>
    </div>
  </div>
  <!-- Default form subscription -->
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="bower_components/jquery/dist/jquery.min.js"></script>
  <script src="bower_components/popper.js/dist/popper.min.js"></script>
  <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>
